env:
  browser: true
  es6: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 2020
  sourceType: 'module'
globals:
  require: false
  nw: false
  globalThis: false
  window: false

  PIXI: false
  Utils: false
  Graphics: false
  TouchInput: false
  Input: false
  Tilemap: false
  Bitmap: false
  JsonEx: false
  Rectangle: false
  Point: false
  Sprite: false
  TilingSprite: false

  PluginManager: false
  ImageManager: false
  DataManager: false
  SceneManager: false
  SoundManager: false
  ColorManager: false

  Scene_Base: false
  Scene_Map: false
  Scene_Menu: false
  Scene_MenuBase: false
  Scene_Boot: false
  Spriteset_Map: false
  Sprite_Clickable: false
  Sprite_Balloon: false
  Sprite_Animation: false

  Game_Player: false
  Game_Event: false
  Game_Map: false
  Game_Variables: false
  Game_Interpreter: false
  Game_Party: false

  Window_Base: false
  Window_Selectable: false
  Window_Command: false
  Window_Scrollable: false
  Window_MapName: false

  $gameMap: false
  $gamePlayer: false
  $gameTemp: false
  $plugins: false
  $gameMessage: false
  $gameVariables: false
  $gameSwitches: false
  $gameScreen: false

  $dataCommonEvents: false
  $dataMap: false

  CyclonePlugin: true
  CycloneMapEditor: true
  CycloneMaps: true
  CycloneTime: true
rules:
  indent:
    - warn
    - 2
    -
      SwitchCase: 1
  linebreak-style:
    - off
    # - error
    # - windows
  quotes:
    - error
    - single
    - avoidEscape: true
  semi:
    - error
    - always
  no-control-regex:
    - warn
  no-unreachable:
    - warn
  no-undef:
    - error
  no-unused-vars:
    - error
    -
      args: none
  no-constant-condition:
    - error
    -
      checkLoops: false
  no-prototype-builtins:
    - off
  block-scoped-var:
    - warn
  complexity:
    - error
    - 10
  no-return-assign:
    - warn
  no-return-await:
    - error
  no-self-compare:
    - error
  no-throw-literal:
    - error
  no-sequences:
    - error
  camelcase:
    - warn
    - ignoreGlobals: true
  max-depth:
    - error
  multiline-ternary:
    - error
    - never
  no-multiple-empty-lines:
    - error
  no-multi-assign:
    - error
  no-new-object:
    - error
  no-tabs:
    - error
  operator-linebreak:
    - error
    - none
  arrow-spacing:
    - error
  no-var:
    - error
  prefer-arrow-callback:
    - error
  object-shorthand:
    - error
  rest-spread-spacing:
    - error